-- ========================================================
-- Mandori AI Chatbot - Supabase Database Schema
-- Supabase 대시보드 > SQL Editor 에서 아래 코드를 실행하세요.
-- ========================================================

-- 1. chat_logs 테이블 생성
CREATE TABLE IF NOT EXISTS public.chat_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_message TEXT NOT NULL,
    bot_response TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 인덱스 추가 (최신 대화순 조회 성능 향상)
CREATE INDEX IF NOT EXISTS idx_chat_logs_created_at ON public.chat_logs (created_at DESC);

-- 3. Row Level Security (RLS) 설정
ALTER TABLE public.chat_logs ENABLE ROW LEVEL SECURITY;

-- 기존 정책이 있을 경우 삭제 후 재생성 (재실행 에러 방지)
DROP POLICY IF EXISTS "Allow serverless insert" ON public.chat_logs;
DROP POLICY IF EXISTS "Allow select for authenticated" ON public.chat_logs;

-- 백엔드(Serverless Function)에서 anon/service_role 키를 통한 INSERT 허용 정책
CREATE POLICY "Allow serverless insert" 
ON public.chat_logs 
FOR INSERT 
WITH CHECK (true);

-- (선택 사항) 대화 로그 조회가 필요한 경우 허용 정책
CREATE POLICY "Allow select for authenticated" 
ON public.chat_logs 
FOR SELECT 
USING (true);

COMMENT ON TABLE public.chat_logs IS 'AI 챗봇 대화 기록 테이블';
